name: Deploy pages
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Build
        run: npm run build
      - name: Public
        run: ls
        run: cp -a micro-frontend-practice/slidev/dist/. micro-frontend-practice/slidev/public/