[build.environment]
  NODE_VERSION = "14"

[build]
  publish = "micro-frontend-practice/slidev/dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/micro-frontend-practice/slidev/dist/index.html"
  status = 200
